# Generated by Django 2.1.2 on 2018-10-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Tweet_id', models.CharField(max_length=255)),
                ('Tweet_id_str', models.CharField(max_length=255)),
                ('Tweet_Date', models.DateTimeField()),
                ('Tweet_Text', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Zappy_Tweet',
            },
        ),
    ]
